### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by yuyan884** [YuyaHayashiBr/furima-38296#47]
# What
フリマアプリの挙動確認依頼

# Why
最終課題であるフリマアプリを実装しましたので、挙動確認をお願い致します。

# URL
https://furima-38296.herokuapp.com/

# Basic認証のIDとパスワード
ID: admin
PW: 2222

# 出品者用のメールアドレスとパスワード
E-mail: guest@guest.com
PW: aaa111

# 購入者用のメールアドレスとパスワード
E-mail: guest2@guest2.com
PW: aaa222

**Comment by snkw-works** [comment]
@YuyaHayashiBr さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！ **LGTM** です✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
**※Github上の最終課題の履歴はここまで頑張ってきた証です。削除せず大切に保管するようにしましょう。**

![lgtm_01](https://user-images.githubusercontent.com/54050089/186354234-2de2a3d1-500d-4164-81d5-7585cdd03227.png)

**Comment by yuyan884** [comment]
@snkw-works 

LGTMありがとうございます。
本件、クローズ致します。

今後は、こちらで学んだ経験を活かし、技術力を磨いていきたいと思います。
